{{- if .Values.deepfenceKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deepfence-cloud-scanner.fullname" . }}-key
  labels:
    {{- include "deepfence-cloud-scanner.labels" . | nindent 4 }}
type: Opaque
data:
  deepfence-key: {{ required "deepfenceKey.key is required" .Values.deepfenceKey.key | b64enc }}
{{- end }}
